package reporting

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"github.com/urb4n3/undertaker/internal/models"
)

// GenerateMarkdown produces the full Markdown report from an AnalysisReport.
func GenerateMarkdown(report *models.AnalysisReport) string {
	var b strings.Builder

	fileName := filepath.Base(report.Sample.Path)

	b.WriteString("# Undertaker Static Analysis Report\n")
	b.WriteString(fmt.Sprintf("## %s\n\n", fileName))

	// Summary section — top findings.
	writeSummary(&b, report)

	// Identity.
	writeIdentity(&b, report)

	// Exports (DLLs).
	writeExports(&b, report)

	// Rich Header.
	writeRichHeader(&b, report)

	// Overlay.
	writeOverlay(&b, report)

	// Packing Assessment.
	writePacking(&b, report)

	// Suspicious Imports.
	writeImports(&b, report)

	// Strings of Interest.
	writeStrings(&b, report)

	// IOCs.
	writeIOCs(&b, report)

	// Capabilities.
	writeCapabilities(&b, report)

	// YARA Matches.
	writeYARAMatches(&b, report)

	// .NET Metadata.
	writeDotNet(&b, report)

	// Analyzer Errors.
	writeErrors(&b, report)

	// Footer.
	b.WriteString(fmt.Sprintf("\n---\n*Generated by Undertaker at %s*\n",
		time.Now().UTC().Format("2006-01-02 15:04:05 UTC")))

	return b.String()
}

func writeSummary(b *strings.Builder, report *models.AnalysisReport) {
	b.WriteString("### Summary\n")

	var findings []string

	// File type.
	findings = append(findings, fmt.Sprintf("**File type:** %s", report.Sample.FileType))

	// Packing.
	if report.Packing.Confidence != "" && report.Packing.Confidence != "none" {
		detail := report.Packing.Label
		if report.Packing.PackerName != "" {
			detail += " (" + report.Packing.PackerName + ")"
		}
		findings = append(findings, fmt.Sprintf("**Packing:** %s", detail))
	}

	// Import-derived capabilities.
	if len(report.Imports.CapabilityTags) > 0 {
		findings = append(findings, fmt.Sprintf("**Suspicious capabilities:** %s",
			strings.Join(report.Imports.CapabilityTags, ", ")))
	}

	// IOC count.
	if len(report.IOCs) > 0 {
		findings = append(findings, fmt.Sprintf("**IOCs found:** %d", len(report.IOCs)))
	}

	// YARA matches.
	if len(report.YARAMatches) > 0 {
		var names []string
		for _, m := range report.YARAMatches {
			names = append(names, m.RuleName)
		}
		findings = append(findings, fmt.Sprintf("**YARA matches:** %s", strings.Join(names, ", ")))
	}

	// Overlay.
	if report.Overlay != nil && report.Overlay.Size > 0 {
		findings = append(findings, fmt.Sprintf("**Overlay:** %s appended data (entropy %.2f)",
			humanSize(report.Overlay.Size), report.Overlay.Entropy))
	}

	// Capa capabilities.
	capaCount := 0
	for _, c := range report.Capabilities {
		if c.Source == "capa" {
			capaCount++
		}
	}
	if capaCount > 0 {
		findings = append(findings, fmt.Sprintf("**capa capabilities:** %d techniques detected", capaCount))
	}

	// String extraction warnings.
	hasFLOSS := false
	for _, s := range report.Strings {
		if strings.HasPrefix(s.Source, "floss_") {
			hasFLOSS = true
			break
		}
	}
	if !hasFLOSS {
		findings = append(findings, "**Note:** Strings extracted without FLOSS — XOR-encoded, stack-constructed, and obfuscated strings may be missing")
	}
	if !hasFLOSS && report.Packing.Confidence != "" && report.Packing.Confidence != "none" {
		findings = append(findings, "**Warning:** Sample appears packed and FLOSS is not available — string results are likely incomplete")
	}
	if len(report.Strings) > 0 && len(report.Strings) < 10 {
		findings = append(findings, "**Warning:** Unusually few strings extracted — sample may be packed or obfuscated")
	}

	// Capabilities from imports only (no capa).
	if capaCount == 0 && len(report.Capabilities) > 0 {
		findings = append(findings, "**Note:** Capabilities derived from imports only — install capa for ATT&CK technique mapping")
	}

	// Errors.
	if len(report.Errors) > 0 {
		findings = append(findings, fmt.Sprintf("**Analyzer errors:** %d (see Errors section)", len(report.Errors)))
	}

	for _, f := range findings {
		b.WriteString(fmt.Sprintf("- %s\n", f))
	}
	b.WriteString("\n")
}

func writeIdentity(b *strings.Builder, report *models.AnalysisReport) {
	s := &report.Sample
	m := &report.Metadata

	b.WriteString("### Identity\n")
	b.WriteString(fmt.Sprintf("- **SHA256:** `%s`\n", s.SHA256))
	b.WriteString(fmt.Sprintf("- **MD5:** `%s`\n", s.MD5))
	b.WriteString(fmt.Sprintf("- **SHA1:** `%s`\n", s.SHA1))
	b.WriteString(fmt.Sprintf("- **ssdeep:** `%s`\n", s.SSDeep))
	if s.ImpHash != "" {
		b.WriteString(fmt.Sprintf("- **imphash:** `%s`\n", s.ImpHash))
	}
	b.WriteString(fmt.Sprintf("- **File type:** %s\n", s.FileType))
	if s.Architecture != "" {
		b.WriteString(fmt.Sprintf("- **Architecture:** %s\n", s.Architecture))
	}
	b.WriteString(fmt.Sprintf("- **File size:** %s (%d bytes)\n", humanSize(s.FileSize), s.FileSize))

	if !m.CompileTimestamp.IsZero() {
		b.WriteString(fmt.Sprintf("- **Compile timestamp:** %s\n",
			m.CompileTimestamp.UTC().Format("2006-01-02 15:04:05 UTC")))
	}
	if m.TimestampAnomaly != "" {
		b.WriteString(fmt.Sprintf("- **Timestamp anomaly:** %s\n", m.TimestampAnomaly))
	} else if !m.CompileTimestamp.IsZero() {
		b.WriteString("- **Timestamp anomaly:** none\n")
	}

	// Version info.
	if len(m.VersionInfo) > 0 {
		b.WriteString("- **Version info:**\n")
		for k, v := range m.VersionInfo {
			b.WriteString(fmt.Sprintf("  - %s: %s\n", k, v))
		}
	}

	// Debug info — skip entries with empty values.
	if len(m.DebugInfo) > 0 {
		for _, d := range m.DebugInfo {
			if d.Value == "" {
				continue
			}
			b.WriteString(fmt.Sprintf("- **Debug (%s):** `%s`\n", d.Type, d.Value))
		}
	}

	b.WriteString("\n")
}

func writeExports(b *strings.Builder, report *models.AnalysisReport) {
	if len(report.Exports) == 0 {
		return
	}
	b.WriteString("### Exports\n")
	for _, e := range report.Exports {
		line := fmt.Sprintf("- %s (ordinal %d)", e.Name, e.Ordinal)
		if e.Forwarded != "" {
			line += fmt.Sprintf(" → %s", e.Forwarded)
		}
		b.WriteString(line + "\n")
	}
	b.WriteString("\n")
}

func writeRichHeader(b *strings.Builder, report *models.AnalysisReport) {
	if report.RichHeader == nil || len(report.RichHeader.Entries) == 0 {
		return
	}
	b.WriteString("### Rich Header\n")
	for _, e := range report.RichHeader.Entries {
		b.WriteString(fmt.Sprintf("- %s %s (×%d)\n", e.Toolchain, e.Type, e.Count))
	}
	b.WriteString(fmt.Sprintf("- %d unique toolchain entries\n\n", len(report.RichHeader.Entries)))
}

func writeOverlay(b *strings.Builder, report *models.AnalysisReport) {
	if report.Overlay == nil || report.Overlay.Size == 0 {
		return
	}
	b.WriteString("### Overlay\n")
	b.WriteString(fmt.Sprintf("- Overlay detected: %s after last section\n", humanSize(report.Overlay.Size)))
	label := "normal"
	if report.Overlay.Entropy > 7.0 {
		label = "high — likely encrypted or compressed payload"
	} else if report.Overlay.Entropy > 6.0 {
		label = "elevated"
	}
	b.WriteString(fmt.Sprintf("- Overlay entropy: %.2f (%s)\n\n", report.Overlay.Entropy, label))
}

func writePacking(b *strings.Builder, report *models.AnalysisReport) {
	p := &report.Packing
	if p.Confidence == "" {
		return
	}

	b.WriteString("### Packing Assessment\n")
	b.WriteString(fmt.Sprintf("- **Confidence:** %s\n", p.Label))
	if p.PackerName != "" {
		b.WriteString(fmt.Sprintf("- **Packer:** %s\n", p.PackerName))
	}
	b.WriteString(fmt.Sprintf("- **Overall entropy:** %.2f\n", p.Entropy))

	if len(report.Metadata.Sections) > 0 {
		b.WriteString("- **Section entropies:**\n")
		for _, s := range report.Metadata.Sections {
			label := "normal"
			if s.Entropy > 7.0 {
				label = "high"
			} else if s.Entropy > 6.8 {
				label = "elevated"
			}
			b.WriteString(fmt.Sprintf("  - %s: %.2f (%s)\n", s.Name, s.Entropy, label))
		}
	}

	if len(p.Signals) > 0 {
		b.WriteString("- **Signals:** ")
		b.WriteString(strings.Join(p.Signals, "; "))
		b.WriteString("\n")
	}
	b.WriteString("\n")
}

func writeImports(b *strings.Builder, report *models.AnalysisReport) {
	imp := &report.Imports

	b.WriteString("### Imports\n")
	b.WriteString(fmt.Sprintf("- **Total imports:** %d\n", imp.TotalImports))

	if len(imp.SuspiciousImports) == 0 {
		b.WriteString("- No suspicious imports identified\n\n")
		return
	}

	// Group by capability.
	groups := make(map[string][]string)
	var order []string
	for _, si := range imp.SuspiciousImports {
		if _, seen := groups[si.Capability]; !seen {
			order = append(order, si.Capability)
		}
		groups[si.Capability] = append(groups[si.Capability], si.Name)
	}

	b.WriteString("\n**Suspicious Imports:**\n")
	for _, cap := range order {
		apis := groups[cap]
		b.WriteString(fmt.Sprintf("- **%s:** %s\n", formatCapability(cap), strings.Join(apis, ", ")))
	}
	b.WriteString("\n")
}

func writeStrings(b *strings.Builder, report *models.AnalysisReport) {
	if len(report.Strings) == 0 {
		b.WriteString("### Strings of Interest\nNo interesting strings extracted.\n\n")
		return
	}

	b.WriteString("### Strings of Interest\n")

	// Group by category.
	groups := make(map[string][]models.StringHit)
	var order []string
	for _, s := range report.Strings {
		cat := s.Category
		if cat == "" {
			cat = "uncategorized"
		}
		if _, seen := groups[cat]; !seen {
			order = append(order, cat)
		}
		groups[cat] = append(groups[cat], s)
	}

	for _, cat := range order {
		hits := groups[cat]
		b.WriteString(fmt.Sprintf("\n**%s:**\n", formatCategory(cat)))
		for _, h := range hits {
			source := ""
			if strings.HasPrefix(h.Source, "floss_") {
				source = fmt.Sprintf(" [%s]", h.Source)
			} else if h.Source == "base64_decoded" {
				source = " [base64]"
			}
			b.WriteString(fmt.Sprintf("- `%s`%s\n", truncateString(h.Value, 120), source))
		}
	}
	b.WriteString("\n")
}

func writeIOCs(b *strings.Builder, report *models.AnalysisReport) {
	if len(report.IOCs) == 0 {
		return
	}

	b.WriteString("### IOCs\n")
	b.WriteString("| Type | Value | Source |\n")
	b.WriteString("|------|-------|--------|\n")
	for _, ioc := range report.IOCs {
		b.WriteString(fmt.Sprintf("| %s | `%s` | %s |\n",
			ioc.Type, truncateString(ioc.Value, 80), ioc.Source))
	}
	b.WriteString("\n")
}

func writeCapabilities(b *strings.Builder, report *models.AnalysisReport) {
	if len(report.Capabilities) == 0 {
		return
	}

	b.WriteString("### Capabilities\n")

	// Separate capa vs import-derived.
	var capaCaps, importCaps []models.Capability
	for _, c := range report.Capabilities {
		if c.Source == "capa" {
			capaCaps = append(capaCaps, c)
		} else {
			importCaps = append(importCaps, c)
		}
	}

	if len(capaCaps) > 0 {
		// Split into ATT&CK-mapped and behavioral capabilities.
		var attackMapped, behavioral []models.Capability
		for _, c := range capaCaps {
			if c.TechniqueID != "" {
				attackMapped = append(attackMapped, c)
			} else {
				behavioral = append(behavioral, c)
			}
		}

		if len(attackMapped) > 0 {
			b.WriteString("\n**capa — ATT&CK techniques:**\n")
			for _, c := range attackMapped {
				b.WriteString(fmt.Sprintf("- **%s:** %s\n", c.TechniqueID, c.TechniqueName))
			}
		}
		if len(behavioral) > 0 {
			b.WriteString("\n**capa — behavioral capabilities:**\n")
			for _, c := range behavioral {
				b.WriteString(fmt.Sprintf("- %s\n", c.TechniqueName))
			}
		}
	}

	if len(importCaps) > 0 {
		b.WriteString("\n**Import-derived capabilities:**\n")
		for _, c := range importCaps {
			if c.TechniqueID != "" {
				b.WriteString(fmt.Sprintf("- **%s:** %s\n", c.TechniqueID, formatCapability(c.TechniqueName)))
			} else {
				b.WriteString(fmt.Sprintf("- %s\n", formatCapability(c.TechniqueName)))
			}
		}
	}
	b.WriteString("\n")
}

func writeYARAMatches(b *strings.Builder, report *models.AnalysisReport) {
	if len(report.YARAMatches) == 0 {
		return
	}

	b.WriteString("### YARA Matches\n")
	for _, m := range report.YARAMatches {
		line := fmt.Sprintf("- **%s**", m.RuleName)
		if m.Description != "" {
			line += ": " + m.Description
		}
		if len(m.Tags) > 0 {
			line += fmt.Sprintf(" [%s]", strings.Join(m.Tags, ", "))
		}
		b.WriteString(line + "\n")
	}
	b.WriteString("\n")
}

func writeDotNet(b *strings.Builder, report *models.AnalysisReport) {
	if report.DotNet == nil {
		return
	}
	dn := report.DotNet

	b.WriteString("### .NET Metadata\n")
	if dn.RuntimeVersion != "" {
		b.WriteString(fmt.Sprintf("- **Runtime:** %s\n", dn.RuntimeVersion))
	}
	if len(dn.AssemblyRefs) > 0 {
		b.WriteString(fmt.Sprintf("- **Assembly references:** %s\n", strings.Join(dn.AssemblyRefs, ", ")))
	}
	if len(dn.Namespaces) > 0 {
		b.WriteString(fmt.Sprintf("- **Namespaces:** %s\n", strings.Join(dn.Namespaces, ", ")))
	}
	if len(dn.Classes) > 0 {
		b.WriteString(fmt.Sprintf("- **Classes:** %d\n", len(dn.Classes)))
		// Show first 20 classes max.
		limit := len(dn.Classes)
		if limit > 20 {
			limit = 20
		}
		for _, c := range dn.Classes[:limit] {
			b.WriteString(fmt.Sprintf("  - %s.%s (%d methods)\n", c.Namespace, c.Name, len(c.Methods)))
		}
		if len(dn.Classes) > 20 {
			b.WriteString(fmt.Sprintf("  - ... and %d more\n", len(dn.Classes)-20))
		}
	}
	if len(dn.Resources) > 0 {
		b.WriteString(fmt.Sprintf("- **Embedded resources:** %d\n", len(dn.Resources)))
		for _, r := range dn.Resources {
			b.WriteString(fmt.Sprintf("  - %s (%s)\n", r.Name, humanSize(int64(r.Size))))
		}
	}
	b.WriteString("\n")
}

func writeErrors(b *strings.Builder, report *models.AnalysisReport) {
	if len(report.Errors) == 0 {
		return
	}

	b.WriteString("### Analyzer Errors\n")
	for _, e := range report.Errors {
		b.WriteString(fmt.Sprintf("- **%s:** %s\n", e.Analyzer, e.Error))
		if e.Stderr != "" {
			b.WriteString(fmt.Sprintf("  ```\n  %s\n  ```\n", e.Stderr))
		}
	}
	b.WriteString("\n")
}

// --- Helpers ---

func humanSize(bytes int64) string {
	switch {
	case bytes >= 1024*1024*1024:
		return fmt.Sprintf("%.2f GB", float64(bytes)/(1024*1024*1024))
	case bytes >= 1024*1024:
		return fmt.Sprintf("%.2f MB", float64(bytes)/(1024*1024))
	case bytes >= 1024:
		return fmt.Sprintf("%.1f KB", float64(bytes)/1024)
	default:
		return fmt.Sprintf("%d bytes", bytes)
	}
}

func truncateString(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}

func formatCapability(s string) string {
	return strings.ReplaceAll(strings.Title(strings.ReplaceAll(s, "_", " ")), " ", " ")
}

func formatCategory(s string) string {
	replacer := strings.NewReplacer(
		"c2", "C2/Network",
		"filesystem", "Filesystem",
		"registry", "Registry",
		"crypto", "Crypto",
		"mutex", "Mutex/Named Pipes",
		"debug", "Debug",
		"uncategorized", "Other",
	)
	result := replacer.Replace(s)
	if result == s {
		// No replacement found — title case it.
		return strings.Title(s)
	}
	return result
}
