package reporting

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"github.com/urb4n3/undertaker/internal/models"
)

// GenerateMarkdown produces the full Markdown report from an AnalysisReport.
func GenerateMarkdown(report *models.AnalysisReport) string {
	var b strings.Builder

	fileName := filepath.Base(report.Sample.Path)

	b.WriteString("# Undertaker Analysis Report\n")
	b.WriteString(fmt.Sprintf("## %s\n\n", fileName))

	// Summary section — top findings.
	writeSummary(&b, report)

	// Identity.
	writeIdentity(&b, report)

	// Exports (DLLs).
	writeExports(&b, report)

	// Rich Header.
	writeRichHeader(&b, report)

	// Overlay.
	writeOverlay(&b, report)

	// Packing Assessment.
	writePacking(&b, report)

	// Suspicious Imports.
	writeImports(&b, report)

	// Script Analysis.
	writeScript(&b, report)

	// LNK Analysis.
	writeLNK(&b, report)

	// Document Analysis.
	writeDocument(&b, report)

	// Network Analysis.
	writeNetwork(&b, report)

	// Log Analysis.
	writeLog(&b, report)

	// Strings of Interest.
	writeStrings(&b, report)

	// IOCs.
	writeIOCs(&b, report)

	// Capabilities.
	writeCapabilities(&b, report)

	// YARA Matches.
	writeYARAMatches(&b, report)

	// .NET Metadata.
	writeDotNet(&b, report)

	// Analyzer Errors.
	writeErrors(&b, report)

	// Footer.
	b.WriteString(fmt.Sprintf("\n---\n*Generated by Undertaker at %s*\n",
		time.Now().UTC().Format("2006-01-02 15:04:05 UTC")))

	return b.String()
}

func writeSummary(b *strings.Builder, report *models.AnalysisReport) {
	b.WriteString("### Summary\n")

	var findings []string

	// File type.
	findings = append(findings, fmt.Sprintf("**File type:** %s", report.Sample.FileType))

	// Packing.
	if report.Packing.Confidence != "" && report.Packing.Confidence != "none" {
		detail := report.Packing.Label
		if report.Packing.PackerName != "" {
			detail += " (" + report.Packing.PackerName + ")"
		}
		findings = append(findings, fmt.Sprintf("**Packing:** %s", detail))
	}

	// Import-derived capabilities.
	if len(report.Imports.CapabilityTags) > 0 {
		findings = append(findings, fmt.Sprintf("**Suspicious capabilities:** %s",
			strings.Join(report.Imports.CapabilityTags, ", ")))
	}

	// IOC count.
	if len(report.IOCs) > 0 {
		findings = append(findings, fmt.Sprintf("**IOCs found:** %d", len(report.IOCs)))
	}

	// YARA matches.
	if len(report.YARAMatches) > 0 {
		var names []string
		for _, m := range report.YARAMatches {
			names = append(names, m.RuleName)
		}
		findings = append(findings, fmt.Sprintf("**YARA matches:** %s", strings.Join(names, ", ")))
	}

	// Overlay.
	if report.Overlay != nil && report.Overlay.Size > 0 {
		findings = append(findings, fmt.Sprintf("**Overlay:** %s appended data (entropy %.2f)",
			humanSize(report.Overlay.Size), report.Overlay.Entropy))
	}

	// Capa capabilities.
	capaCount := 0
	for _, c := range report.Capabilities {
		if c.Source == "capa" {
			capaCount++
		}
	}
	if capaCount > 0 {
		findings = append(findings, fmt.Sprintf("**capa capabilities:** %d techniques detected", capaCount))
	}

	// String extraction warnings.
	hasFLOSS := false
	for _, s := range report.Strings {
		if strings.HasPrefix(s.Source, "floss_") {
			hasFLOSS = true
			break
		}
	}
	if !hasFLOSS {
		findings = append(findings, "**Note:** Strings extracted without FLOSS — XOR-encoded, stack-constructed, and obfuscated strings may be missing")
	}
	if !hasFLOSS && report.Packing.Confidence != "" && report.Packing.Confidence != "none" {
		findings = append(findings, "**Warning:** Sample appears packed and FLOSS is not available — string results are likely incomplete")
	}
	if len(report.Strings) > 0 && len(report.Strings) < 10 {
		findings = append(findings, "**Warning:** Unusually few strings extracted — sample may be packed or obfuscated")
	}

	// Capabilities from imports only (no capa).
	if capaCount == 0 && len(report.Capabilities) > 0 {
		findings = append(findings, "**Note:** Capabilities derived from imports only — install capa for ATT&CK technique mapping")
	}

	// Script analysis findings.
	if report.Script != nil {
		findings = append(findings, fmt.Sprintf("**Script language:** %s", report.Script.Language))
		if len(report.Script.DangerousCalls) > 0 {
			findings = append(findings, fmt.Sprintf("**Dangerous calls:** %d", len(report.Script.DangerousCalls)))
		}
		if len(report.Script.EncodingLayers) > 0 {
			findings = append(findings, fmt.Sprintf("**Encoding/obfuscation layers:** %d", len(report.Script.EncodingLayers)))
		}
		if len(report.Script.DownloadCradles) > 0 {
			findings = append(findings, fmt.Sprintf("**Download cradles:** %d", len(report.Script.DownloadCradles)))
		}
	}

	// LNK analysis findings.
	if report.LNK != nil {
		if report.LNK.TargetPath != "" {
			findings = append(findings, fmt.Sprintf("**LNK target:** `%s`", report.LNK.TargetPath))
		}
		if report.LNK.Arguments != "" {
			findings = append(findings, fmt.Sprintf("**LNK arguments:** `%s`", truncateString(report.LNK.Arguments, 100)))
		}
		if report.LNK.HasAppendedData {
			findings = append(findings, fmt.Sprintf("**LNK appended data:** %s", humanSize(report.LNK.AppendedSize)))
		}
	}

	// Document analysis findings.
	if report.Document != nil {
		if report.Document.HasMacros {
			findings = append(findings, "**Macros detected:** YES")
		}
		if len(report.Document.MacroKeywords) > 0 {
			findings = append(findings, fmt.Sprintf("**Suspicious macro keywords:** %d", len(report.Document.MacroKeywords)))
		}
	}

	// Network analysis findings.
	if report.Network != nil {
		findings = append(findings, fmt.Sprintf("**Network packets:** %d", report.Network.TotalPackets))
		if len(report.Network.DNSQueries) > 0 {
			findings = append(findings, fmt.Sprintf("**DNS queries:** %d unique domains", len(report.Network.DNSQueries)))
		}
		if len(report.Network.HTTPRequests) > 0 {
			findings = append(findings, fmt.Sprintf("**HTTP requests:** %d", len(report.Network.HTTPRequests)))
		}
		if len(report.Network.Beacons) > 0 {
			findings = append(findings, fmt.Sprintf("**Potential beacons:** %d patterns", len(report.Network.Beacons)))
		}
	}

	// Log analysis findings.
	if report.Log != nil {
		findings = append(findings, fmt.Sprintf("**Log format:** %s", report.Log.Format))
		findings = append(findings, fmt.Sprintf("**Log entries:** %d", report.Log.TotalEntries))
		if len(report.Log.FlaggedEvents) > 0 {
			findings = append(findings, fmt.Sprintf("**Flagged events:** %d", len(report.Log.FlaggedEvents)))
		}
		if len(report.Log.KeywordHits) > 0 {
			findings = append(findings, fmt.Sprintf("**Suspicious keywords:** %d", len(report.Log.KeywordHits)))
		}
	}

	// Errors.
	if len(report.Errors) > 0 {
		findings = append(findings, fmt.Sprintf("**Analyzer errors:** %d (see Errors section)", len(report.Errors)))
	}

	for _, f := range findings {
		b.WriteString(fmt.Sprintf("- %s\n", f))
	}
	b.WriteString("\n")
}

func writeIdentity(b *strings.Builder, report *models.AnalysisReport) {
	s := &report.Sample
	m := &report.Metadata

	b.WriteString("### Identity\n")
	b.WriteString(fmt.Sprintf("- **SHA256:** `%s`\n", s.SHA256))
	b.WriteString(fmt.Sprintf("- **MD5:** `%s`\n", s.MD5))
	b.WriteString(fmt.Sprintf("- **SHA1:** `%s`\n", s.SHA1))
	b.WriteString(fmt.Sprintf("- **ssdeep:** `%s`\n", s.SSDeep))
	if s.ImpHash != "" {
		b.WriteString(fmt.Sprintf("- **imphash:** `%s`\n", s.ImpHash))
	}
	b.WriteString(fmt.Sprintf("- **File type:** %s\n", s.FileType))
	if s.Architecture != "" {
		b.WriteString(fmt.Sprintf("- **Architecture:** %s\n", s.Architecture))
	}
	b.WriteString(fmt.Sprintf("- **File size:** %s (%d bytes)\n", humanSize(s.FileSize), s.FileSize))

	if !m.CompileTimestamp.IsZero() {
		b.WriteString(fmt.Sprintf("- **Compile timestamp:** %s\n",
			m.CompileTimestamp.UTC().Format("2006-01-02 15:04:05 UTC")))
	}
	if m.TimestampAnomaly != "" {
		b.WriteString(fmt.Sprintf("- **Timestamp anomaly:** %s\n", m.TimestampAnomaly))
	} else if !m.CompileTimestamp.IsZero() {
		b.WriteString("- **Timestamp anomaly:** none\n")
	}

	// Version info.
	if len(m.VersionInfo) > 0 {
		b.WriteString("- **Version info:**\n")
		for k, v := range m.VersionInfo {
			b.WriteString(fmt.Sprintf("  - %s: %s\n", k, v))
		}
	}

	// Debug info — skip entries with empty values.
	if len(m.DebugInfo) > 0 {
		for _, d := range m.DebugInfo {
			if d.Value == "" {
				continue
			}
			b.WriteString(fmt.Sprintf("- **Debug (%s):** `%s`\n", d.Type, d.Value))
		}
	}

	b.WriteString("\n")
}

func writeExports(b *strings.Builder, report *models.AnalysisReport) {
	if len(report.Exports) == 0 {
		return
	}
	b.WriteString("### Exports\n")
	for _, e := range report.Exports {
		line := fmt.Sprintf("- %s (ordinal %d)", e.Name, e.Ordinal)
		if e.Forwarded != "" {
			line += fmt.Sprintf(" → %s", e.Forwarded)
		}
		b.WriteString(line + "\n")
	}
	b.WriteString("\n")
}

func writeRichHeader(b *strings.Builder, report *models.AnalysisReport) {
	if report.RichHeader == nil || len(report.RichHeader.Entries) == 0 {
		return
	}
	b.WriteString("### Rich Header\n")
	for _, e := range report.RichHeader.Entries {
		b.WriteString(fmt.Sprintf("- %s %s (×%d)\n", e.Toolchain, e.Type, e.Count))
	}
	b.WriteString(fmt.Sprintf("- %d unique toolchain entries\n\n", len(report.RichHeader.Entries)))
}

func writeOverlay(b *strings.Builder, report *models.AnalysisReport) {
	if report.Overlay == nil || report.Overlay.Size == 0 {
		return
	}
	b.WriteString("### Overlay\n")
	b.WriteString(fmt.Sprintf("- Overlay detected: %s after last section\n", humanSize(report.Overlay.Size)))
	label := "normal"
	if report.Overlay.Entropy > 7.0 {
		label = "high — likely encrypted or compressed payload"
	} else if report.Overlay.Entropy > 6.0 {
		label = "elevated"
	}
	b.WriteString(fmt.Sprintf("- Overlay entropy: %.2f (%s)\n\n", report.Overlay.Entropy, label))
}

func writePacking(b *strings.Builder, report *models.AnalysisReport) {
	p := &report.Packing
	if p.Confidence == "" {
		return
	}

	b.WriteString("### Packing Assessment\n")
	b.WriteString(fmt.Sprintf("- **Confidence:** %s\n", p.Label))
	if p.PackerName != "" {
		b.WriteString(fmt.Sprintf("- **Packer:** %s\n", p.PackerName))
	}
	b.WriteString(fmt.Sprintf("- **Overall entropy:** %.2f\n", p.Entropy))

	if len(report.Metadata.Sections) > 0 {
		b.WriteString("- **Section entropies:**\n")
		for _, s := range report.Metadata.Sections {
			label := "normal"
			if s.Entropy > 7.0 {
				label = "high"
			} else if s.Entropy > 6.8 {
				label = "elevated"
			}
			b.WriteString(fmt.Sprintf("  - %s: %.2f (%s)\n", s.Name, s.Entropy, label))
		}
	}

	if len(p.Signals) > 0 {
		b.WriteString("- **Signals:** ")
		b.WriteString(strings.Join(p.Signals, "; "))
		b.WriteString("\n")
	}
	b.WriteString("\n")
}

func writeImports(b *strings.Builder, report *models.AnalysisReport) {
	imp := &report.Imports

	b.WriteString("### Imports\n")
	b.WriteString(fmt.Sprintf("- **Total imports:** %d\n", imp.TotalImports))

	if len(imp.SuspiciousImports) == 0 {
		b.WriteString("- No suspicious imports identified\n\n")
		return
	}

	// Group by capability.
	groups := make(map[string][]string)
	var order []string
	for _, si := range imp.SuspiciousImports {
		if _, seen := groups[si.Capability]; !seen {
			order = append(order, si.Capability)
		}
		groups[si.Capability] = append(groups[si.Capability], si.Name)
	}

	b.WriteString("\n**Suspicious Imports:**\n")
	for _, cap := range order {
		apis := groups[cap]
		b.WriteString(fmt.Sprintf("- **%s:** %s\n", formatCapability(cap), strings.Join(apis, ", ")))
	}
	b.WriteString("\n")
}

func writeStrings(b *strings.Builder, report *models.AnalysisReport) {
	if len(report.Strings) == 0 {
		b.WriteString("### Strings of Interest\nNo interesting strings extracted.\n\n")
		return
	}

	b.WriteString("### Strings of Interest\n")

	// Group by category.
	groups := make(map[string][]models.StringHit)
	var order []string
	for _, s := range report.Strings {
		cat := s.Category
		if cat == "" {
			cat = "uncategorized"
		}
		if _, seen := groups[cat]; !seen {
			order = append(order, cat)
		}
		groups[cat] = append(groups[cat], s)
	}

	for _, cat := range order {
		hits := groups[cat]
		b.WriteString(fmt.Sprintf("\n**%s:**\n", formatCategory(cat)))
		for _, h := range hits {
			source := ""
			if strings.HasPrefix(h.Source, "floss_") {
				source = fmt.Sprintf(" [%s]", h.Source)
			} else if h.Source == "base64_decoded" {
				source = " [base64]"
			}
			b.WriteString(fmt.Sprintf("- `%s`%s\n", truncateString(h.Value, 120), source))
		}
	}
	b.WriteString("\n")
}

func writeIOCs(b *strings.Builder, report *models.AnalysisReport) {
	if len(report.IOCs) == 0 {
		return
	}

	b.WriteString("### IOCs\n")
	b.WriteString("| Type | Value | Source |\n")
	b.WriteString("|------|-------|--------|\n")
	for _, ioc := range report.IOCs {
		b.WriteString(fmt.Sprintf("| %s | `%s` | %s |\n",
			ioc.Type, truncateString(ioc.Value, 80), ioc.Source))
	}
	b.WriteString("\n")
}

func writeCapabilities(b *strings.Builder, report *models.AnalysisReport) {
	if len(report.Capabilities) == 0 {
		return
	}

	b.WriteString("### Capabilities\n")

	// Separate capa vs import-derived.
	var capaCaps, importCaps []models.Capability
	for _, c := range report.Capabilities {
		if c.Source == "capa" {
			capaCaps = append(capaCaps, c)
		} else {
			importCaps = append(importCaps, c)
		}
	}

	if len(capaCaps) > 0 {
		// Split into ATT&CK-mapped and behavioral capabilities.
		var attackMapped, behavioral []models.Capability
		for _, c := range capaCaps {
			if c.TechniqueID != "" {
				attackMapped = append(attackMapped, c)
			} else {
				behavioral = append(behavioral, c)
			}
		}

		if len(attackMapped) > 0 {
			b.WriteString("\n**capa — ATT&CK techniques:**\n")
			for _, c := range attackMapped {
				b.WriteString(fmt.Sprintf("- **%s:** %s\n", c.TechniqueID, c.TechniqueName))
			}
		}
		if len(behavioral) > 0 {
			b.WriteString("\n**capa — behavioral capabilities:**\n")
			for _, c := range behavioral {
				b.WriteString(fmt.Sprintf("- %s\n", c.TechniqueName))
			}
		}
	}

	if len(importCaps) > 0 {
		b.WriteString("\n**Import-derived capabilities:**\n")
		for _, c := range importCaps {
			if c.TechniqueID != "" {
				b.WriteString(fmt.Sprintf("- **%s:** %s\n", c.TechniqueID, formatCapability(c.TechniqueName)))
			} else {
				b.WriteString(fmt.Sprintf("- %s\n", formatCapability(c.TechniqueName)))
			}
		}
	}
	b.WriteString("\n")
}

func writeYARAMatches(b *strings.Builder, report *models.AnalysisReport) {
	if len(report.YARAMatches) == 0 {
		return
	}

	b.WriteString("### YARA Matches\n")
	for _, m := range report.YARAMatches {
		line := fmt.Sprintf("- **%s**", m.RuleName)
		if m.Description != "" {
			line += ": " + m.Description
		}
		if len(m.Tags) > 0 {
			line += fmt.Sprintf(" [%s]", strings.Join(m.Tags, ", "))
		}
		b.WriteString(line + "\n")
	}
	b.WriteString("\n")
}

func writeDotNet(b *strings.Builder, report *models.AnalysisReport) {
	if report.DotNet == nil {
		return
	}
	dn := report.DotNet

	b.WriteString("### .NET Metadata\n")
	if dn.RuntimeVersion != "" {
		b.WriteString(fmt.Sprintf("- **Runtime:** %s\n", dn.RuntimeVersion))
	}
	if len(dn.AssemblyRefs) > 0 {
		b.WriteString(fmt.Sprintf("- **Assembly references:** %s\n", strings.Join(dn.AssemblyRefs, ", ")))
	}
	if len(dn.Namespaces) > 0 {
		b.WriteString(fmt.Sprintf("- **Namespaces:** %s\n", strings.Join(dn.Namespaces, ", ")))
	}
	if len(dn.Classes) > 0 {
		b.WriteString(fmt.Sprintf("- **Classes:** %d\n", len(dn.Classes)))
		// Show first 20 classes max.
		limit := len(dn.Classes)
		if limit > 20 {
			limit = 20
		}
		for _, c := range dn.Classes[:limit] {
			b.WriteString(fmt.Sprintf("  - %s.%s (%d methods)\n", c.Namespace, c.Name, len(c.Methods)))
		}
		if len(dn.Classes) > 20 {
			b.WriteString(fmt.Sprintf("  - ... and %d more\n", len(dn.Classes)-20))
		}
	}
	if len(dn.Resources) > 0 {
		b.WriteString(fmt.Sprintf("- **Embedded resources:** %d\n", len(dn.Resources)))
		for _, r := range dn.Resources {
			b.WriteString(fmt.Sprintf("  - %s (%s)\n", r.Name, humanSize(int64(r.Size))))
		}
	}
	b.WriteString("\n")
}

func writeScript(b *strings.Builder, report *models.AnalysisReport) {
	if report.Script == nil {
		return
	}
	s := report.Script

	b.WriteString("### Script Analysis\n")
	b.WriteString(fmt.Sprintf("- **Language:** %s\n", s.Language))
	for k, v := range s.ScriptMetadata {
		b.WriteString(fmt.Sprintf("- **%s:** %s\n", formatCapability(k), v))
	}
	b.WriteString("\n")

	if len(s.DangerousCalls) > 0 {
		b.WriteString("**Dangerous Calls:**\n")
		// Group by capability.
		groups := make(map[string][]models.DangerousCall)
		var order []string
		for _, dc := range s.DangerousCalls {
			if _, seen := groups[dc.Capability]; !seen {
				order = append(order, dc.Capability)
			}
			groups[dc.Capability] = append(groups[dc.Capability], dc)
		}
		for _, cap := range order {
			calls := groups[cap]
			b.WriteString(fmt.Sprintf("\n*%s:*\n", formatCapability(cap)))
			for _, dc := range calls {
				line := fmt.Sprintf("- `%s`", dc.Call)
				if dc.Line > 0 {
					line += fmt.Sprintf(" (line %d)", dc.Line)
				}
				if dc.Context != "" {
					line += fmt.Sprintf(" — `%s`", dc.Context)
				}
				b.WriteString(line + "\n")
			}
		}
		b.WriteString("\n")
	}

	if len(s.EncodingLayers) > 0 {
		b.WriteString("**Encoding/Obfuscation Layers:**\n")
		for _, el := range s.EncodingLayers {
			line := fmt.Sprintf("- **%s:** %s", el.Type, el.Description)
			if el.Sample != "" {
				line += fmt.Sprintf(" — `%s`", el.Sample)
			}
			b.WriteString(line + "\n")
		}
		b.WriteString("\n")
	}

	if len(s.DownloadCradles) > 0 {
		b.WriteString("**Download Cradles:**\n")
		for _, dc := range s.DownloadCradles {
			b.WriteString(fmt.Sprintf("- `%s`\n", dc))
		}
		b.WriteString("\n")
	}
}

func writeLNK(b *strings.Builder, report *models.AnalysisReport) {
	if report.LNK == nil {
		return
	}
	l := report.LNK

	b.WriteString("### LNK Shortcut Analysis\n")
	if l.TargetPath != "" {
		b.WriteString(fmt.Sprintf("- **Target:** `%s`\n", l.TargetPath))
	}
	if l.Arguments != "" {
		b.WriteString(fmt.Sprintf("- **Arguments:** `%s`\n", l.Arguments))
	}
	if l.WorkingDir != "" {
		b.WriteString(fmt.Sprintf("- **Working directory:** `%s`\n", l.WorkingDir))
	}
	if l.Description != "" {
		b.WriteString(fmt.Sprintf("- **Description:** %s\n", l.Description))
	}
	if l.IconLocation != "" {
		b.WriteString(fmt.Sprintf("- **Icon location:** `%s`\n", l.IconLocation))
	}
	if l.ShowCommand != "" {
		b.WriteString(fmt.Sprintf("- **Show command:** %s\n", l.ShowCommand))
	}
	if len(l.Flags) > 0 {
		b.WriteString(fmt.Sprintf("- **Flags:** %s\n", strings.Join(l.Flags, ", ")))
	}
	if l.HasAppendedData {
		b.WriteString(fmt.Sprintf("- **Appended data:** %s (potential embedded payload)\n", humanSize(l.AppendedSize)))
	}
	b.WriteString("\n")
}

func writeDocument(b *strings.Builder, report *models.AnalysisReport) {
	if report.Document == nil {
		return
	}
	d := report.Document

	b.WriteString("### Document Analysis\n")
	if d.Metadata != nil {
		if docFmt, ok := d.Metadata["format"]; ok {
			b.WriteString(fmt.Sprintf("- **Format:** %s\n", docFmt))
		}
	}

	macroLabel := "No"
	if d.HasMacros {
		macroLabel = "**YES**"
	}
	b.WriteString(fmt.Sprintf("- **Macros detected:** %s\n", macroLabel))

	if len(d.Streams) > 0 {
		b.WriteString(fmt.Sprintf("- **OLE streams:** %d\n", len(d.Streams)))
		for _, s := range d.Streams {
			b.WriteString(fmt.Sprintf("  - %s (%s)\n", s.Name, humanSize(s.Size)))
		}
	}
	b.WriteString("\n")

	if len(d.MacroKeywords) > 0 {
		b.WriteString("**Suspicious Macro Keywords:**\n")
		// Group by category.
		groups := make(map[string][]models.MacroKeyword)
		var order []string
		for _, kw := range d.MacroKeywords {
			if _, seen := groups[kw.Category]; !seen {
				order = append(order, kw.Category)
			}
			groups[kw.Category] = append(groups[kw.Category], kw)
		}
		for _, cat := range order {
			keywords := groups[cat]
			b.WriteString(fmt.Sprintf("\n*%s:*\n", formatCapability(cat)))
			for _, kw := range keywords {
				line := fmt.Sprintf("- `%s`", kw.Keyword)
				if kw.Context != "" {
					line += fmt.Sprintf(" — `%s`", kw.Context)
				}
				b.WriteString(line + "\n")
			}
		}
		b.WriteString("\n")
	}
}

func writeNetwork(b *strings.Builder, report *models.AnalysisReport) {
	if report.Network == nil {
		return
	}
	n := report.Network

	b.WriteString("### Network Capture Analysis\n")
	b.WriteString(fmt.Sprintf("- **Total packets:** %d\n", n.TotalPackets))
	if len(n.Protocols) > 0 {
		b.WriteString(fmt.Sprintf("- **Protocols:** %s\n", strings.Join(n.Protocols, ", ")))
	}
	b.WriteString("\n")

	if len(n.DNSQueries) > 0 {
		b.WriteString("**DNS Queries:**\n")
		limit := len(n.DNSQueries)
		if limit > 50 {
			limit = 50
		}
		for _, q := range n.DNSQueries[:limit] {
			line := fmt.Sprintf("- `%s`", q.Domain)
			if q.Answer != "" {
				line += fmt.Sprintf(" → %s", q.Answer)
			}
			b.WriteString(line + "\n")
		}
		if len(n.DNSQueries) > 50 {
			b.WriteString(fmt.Sprintf("- ... and %d more\n", len(n.DNSQueries)-50))
		}
		b.WriteString("\n")
	}

	if len(n.HTTPRequests) > 0 {
		b.WriteString("**HTTP Requests:**\n")
		b.WriteString("| Method | URL | User-Agent |\n")
		b.WriteString("|--------|-----|------------|\n")
		limit := len(n.HTTPRequests)
		if limit > 50 {
			limit = 50
		}
		for _, r := range n.HTTPRequests[:limit] {
			ua := r.UserAgent
			if ua == "" {
				ua = "-"
			}
			b.WriteString(fmt.Sprintf("| %s | `%s` | %s |\n",
				r.Method, truncateString(r.URL, 80), truncateString(ua, 60)))
		}
		b.WriteString("\n")
	}

	if len(n.TLSInfo) > 0 {
		b.WriteString("**TLS Server Names (SNI):**\n")
		limit := len(n.TLSInfo)
		if limit > 30 {
			limit = 30
		}
		for _, t := range n.TLSInfo[:limit] {
			b.WriteString(fmt.Sprintf("- `%s`\n", t.ServerName))
		}
		b.WriteString("\n")
	}

	if len(n.Connections) > 0 {
		b.WriteString("**Top Connections:**\n")
		b.WriteString("| Source | Destination | Proto | Count |\n")
		b.WriteString("|--------|-------------|-------|-------|\n")
		limit := len(n.Connections)
		if limit > 30 {
			limit = 30
		}
		for _, c := range n.Connections[:limit] {
			b.WriteString(fmt.Sprintf("| %s:%d | %s:%d | %s | %d |\n",
				c.SrcIP, c.SrcPort, c.DstIP, c.DstPort, c.Proto, c.Count))
		}
		b.WriteString("\n")
	}

	if len(n.Beacons) > 0 {
		b.WriteString("**Potential Beaconing:**\n")
		for _, beacon := range n.Beacons {
			b.WriteString(fmt.Sprintf("- %s:%d — %d connections\n",
				beacon.DstIP, beacon.DstPort, beacon.Count))
		}
		b.WriteString("\n")
	}
}

func writeLog(b *strings.Builder, report *models.AnalysisReport) {
	if report.Log == nil {
		return
	}
	l := report.Log

	b.WriteString("### Log Analysis\n")
	b.WriteString(fmt.Sprintf("- **Format:** %s\n", l.Format))
	b.WriteString(fmt.Sprintf("- **Total entries:** %d\n", l.TotalEntries))
	if l.TimeRange != nil {
		b.WriteString(fmt.Sprintf("- **Time range:** %s → %s\n", l.TimeRange.Earliest, l.TimeRange.Latest))
	}
	b.WriteString("\n")

	if len(l.TopEventIDs) > 0 {
		b.WriteString("**Top Event IDs:**\n")
		b.WriteString("| Event ID | Description | Count |\n")
		b.WriteString("|----------|-------------|-------|\n")
		for _, e := range l.TopEventIDs {
			b.WriteString(fmt.Sprintf("| %d | %s | %d |\n", e.EventID, e.Description, e.Count))
		}
		b.WriteString("\n")
	}

	if len(l.FlaggedEvents) > 0 {
		b.WriteString("**Flagged Security Events:**\n")
		for _, f := range l.FlaggedEvents {
			line := fmt.Sprintf("- **Event %d:** %s", f.EventID, f.Description)
			if f.Detail != "" {
				line += fmt.Sprintf(" — %s", f.Detail)
			}
			b.WriteString(line + "\n")
		}
		b.WriteString("\n")
	}

	if len(l.KeywordHits) > 0 {
		b.WriteString("**Suspicious Keywords:**\n")
		b.WriteString("| Keyword | Count | Context |\n")
		b.WriteString("|---------|-------|--------|\n")
		for _, kw := range l.KeywordHits {
			b.WriteString(fmt.Sprintf("| `%s` | %d | %s |\n", kw.Keyword, kw.Count, kw.Context))
		}
		b.WriteString("\n")
	}
}

func writeErrors(b *strings.Builder, report *models.AnalysisReport) {
	if len(report.Errors) == 0 {
		return
	}

	b.WriteString("### Analyzer Errors\n")
	for _, e := range report.Errors {
		b.WriteString(fmt.Sprintf("- **%s:** %s\n", e.Analyzer, e.Error))
		if e.Stderr != "" {
			b.WriteString(fmt.Sprintf("  ```\n  %s\n  ```\n", e.Stderr))
		}
	}
	b.WriteString("\n")
}

// --- Helpers ---

func humanSize(bytes int64) string {
	switch {
	case bytes >= 1024*1024*1024:
		return fmt.Sprintf("%.2f GB", float64(bytes)/(1024*1024*1024))
	case bytes >= 1024*1024:
		return fmt.Sprintf("%.2f MB", float64(bytes)/(1024*1024))
	case bytes >= 1024:
		return fmt.Sprintf("%.1f KB", float64(bytes)/1024)
	default:
		return fmt.Sprintf("%d bytes", bytes)
	}
}

func truncateString(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}

func formatCapability(s string) string {
	return strings.ReplaceAll(strings.Title(strings.ReplaceAll(s, "_", " ")), " ", " ")
}

func formatCategory(s string) string {
	replacer := strings.NewReplacer(
		"c2", "C2/Network",
		"filesystem", "Filesystem",
		"registry", "Registry",
		"crypto", "Crypto",
		"mutex", "Mutex/Named Pipes",
		"debug", "Debug",
		"uncategorized", "Other",
	)
	result := replacer.Replace(s)
	if result == s {
		// No replacement found — title case it.
		return strings.Title(s)
	}
	return result
}
